# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.


def fibonacci(hold = [1, 2]):
    hold.append(hold[-1] + hold[-2])
    return hold


def call_fib(n):
    fib = fibonacci()
    while fib[-1] < n:
        fibonacci()
    return fib[:-1]


def sum_if_even(n):
    return sum(i for i in call_fib(n) if i % 2 == 0)


# print(call_fib(90))
print(sum_if_even(90))
